// <auto-generated />
using System;
using DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(BookingContext))]
    partial class BookingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DB.BookingDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAviable")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime>("Reservation")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("BookingTest", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 21, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 21, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 21, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 22, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 22, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 22, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 23, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 23, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 23, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 24, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 24, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 24, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 27, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 27, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 27, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 28, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 28, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 28, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 29, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 29, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 29, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 30, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 30, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 11, 30, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 1, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 1, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 4, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 4, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 4, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 5, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 5, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 5, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 6, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 6, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 6, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 7, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 7, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 7, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 8, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 8, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 8, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 11, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 11, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 11, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 12, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 12, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 12, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 13, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 13, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 51,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 13, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 52,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 14, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 53,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 14, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 54,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 14, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 55,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 15, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 56,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 15, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 57,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 15, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 58,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 18, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 59,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 18, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 60,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 18, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 61,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 19, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 62,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 19, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 63,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 19, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 64,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 20, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 65,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 20, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 66,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 20, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 67,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 21, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 68,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 21, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 69,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 21, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 70,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 22, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 71,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 72,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 22, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 73,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 25, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 74,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 25, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 75,
                            IsAviable = true,
                            Reservation = new DateTime(2023, 12, 25, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
